export const avatars = [
  {
    id: 1,
    src: "VRC image A(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3.5,
    likes: 100,
    price: 5.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 7000,
    supported: true,
  },
  {
    id: 2,
    src: "VRC image B(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 2,
    likes: 100,
    price: 5.0,
    contents: "PC Only",
    gender: "female",
    polygon: 7000,
    supported: false,
  },
  {
    id: 3,
    src: "VRC image C(M).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 10.0,
    contents: "PC Only",
    gender: "male",
    polygon: 8000,
    supported: true,
  },
  {
    id: 4,
    src: "VRC image D(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 4,
    likes: 100,
    price: 10.0,
    contents: "PC Only",
    gender: "female",
    polygon: 9000,
    supported: true,
  },
  {
    id: 5,
    src: "VRC image E(M).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 25.0,
    contents: "PC Only",
    gender: "female",
    polygon: 11000,
    supported: true,
  },
  {
    id: 6,
    src: "VRC image F(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 5,
    likes: 100,
    price: 25.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 12000,
    supported: false,
  },
  {
    id: 7,
    src: "VRC image G(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 35.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 13000,
    supported: true,
  },
  {
    id: 8,
    src: "VRC image H(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 38.0,
    contents: "PC Only",
    gender: "female",
    polygon: 17000,
    supported: true,
  },
  {
    id: 9,
    src: "VRC image I(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 45.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 21000,
    supported: true,
  },
  {
    id: 10,
    src: "VRC image J(M).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 1,
    likes: 100,
    price: 48.0,
    contents: "PC Only",
    gender: "male",
    polygon: 26000,
    supported: true,
  },
  {
    id: 11,
    src: "VRC image K(M).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 60.0,
    contents: "Quest Only",
    gender: "male",
    polygon: 35000,
    supported: true,
  },
  {
    id: 12,
    src: "VRC image L(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 2.5,
    likes: 100,
    price: 65.0,
    contents: "PC Only",
    gender: "female",
    polygon: 40000,
    supported: false,
  },
  {
    id: 13,
    src: "VRC image M(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 500.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 50000,
    supported: true,
  },
  {
    id: 14,
    src: "VRC image N(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 4.5,
    likes: 100,
    price: 500.0,
    contents: "PC Only",
    gender: "female",
    polygon: 45000,
    supported: true,
  },
  {
    id: 15,
    src: "VRC image O(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 50.0,
    contents: "PC Only",
    gender: "female",
    polygon: 100000,
    supported: false,
  },
  {
    id: 16,
    src: "VRC image P(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 55.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 70000,
    supported: true,
  },
  {
    id: 17,
    src: "VRC image Q(M).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 5,
    likes: 100,
    price: 26.0,
    contents: "PC Only",
    gender: "male",
    polygon: 60000,
    supported: true,
  },
  {
    id: 18,
    src: "VRC image R(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 15.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 7000,
    supported: true,
  },
  {
    id: 19,
    src: "VRC image S(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 6.0,
    contents: "PC Only",
    gender: "female",
    polygon: 5000,
    supported: true,
  },
  {
    id: 20,
    src: "VRC image T(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 8.0,
    contents: "PC Only",
    gender: "female",
    polygon: 19000,
    supported: true,
  },
  {
    id: 21,
    src: "VRC image U(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3.5,
    likes: 100,
    price: 30.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 65000,
    supported: true,
  },
  {
    id: 22,
    src: "VRC image V(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 40.0,
    contents: "PC Only",
    gender: "female",
    polygon: 37000,
    supported: true,
  },
  {
    id: 23,
    src: "VRC image W(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 1.5,
    likes: 100,
    price: 36.0,
    contents: "PC Only",
    gender: "female",
    polygon: 55000,
    supported: true,
  },
  {
    id: 24,
    src: "VRC image X(F).png",
    title: 'Avatar name "Avatown" -nice original avatar of Avatown',
    rating: 3,
    likes: 100,
    price: 16.0,
    contents: "Quest Only",
    gender: "female",
    polygon: 90000,
    supported: false,
  },
];





